package menus.menuClasses;

public enum optionsEnum {ADD_MAP,ADD_ZONE,ADD_RECORD,DELETE_MAP,DELETE_ZONE,DELETE_RECORD, VIEW,SEARCH_MAPS,SEARCH_ZONES,
    SEARCH_RECORDS,NEXT,PREVIOUS,NONE,EXIT,VIEW_ZONES,VIEW_RECORDS, WRITE, LOAD};

